# Generated by Django 4.2.13 on 2024-05-20 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_pdf',
            field=models.FileField(default='pdfs/default_pdf.pdf', upload_to='pdfs/'),
        ),
    ]
