# Generated by Django 4.2.13 on 2024-05-21 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_course_course_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_pdf',
            field=models.FileField(default='static/pdfs/default_pdf.pdf', upload_to='static/pdfs/'),
        ),
    ]
