# Generated by Django 4.2.13 on 2024-07-03 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_result_result_id_assignments'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_pdf',
            field=models.FileField(default='static/pdfs/default_pdf.pdf', upload_to='static/pdfs/'),
        ),
    ]
