# Generated by Django 4.2.13 on 2024-05-23 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_quiz_desc_quiz_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz_ques',
            name='ques_id',
            field=models.CharField(max_length=250, primary_key=True, serialize=False),
        ),
    ]
